import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { KNOWLEDGE_BASE_DIR, GROUPS_DIR } from '@bevel-software/platform-shared';
import type { IKbSeedService } from './kb-seed.interface.js';

const execFileAsync = promisify(execFile);

/**
 * Fallback committer identity for seed commits. Mirrors the workspace clone's
 * bot identity so seed commits attribute to the same bot in `git log`.
 */
const BOT_NAME = 'Bevel Workflow';
const BOT_EMAIL = 'bevel-workflow@bevel.software';

/**
 * The **required scaffolding** — the minimum an operational KB needs. When a
 * branch is loaded, any of these that are missing are added to it; the sample
 * ontology is NOT (it only seeds a fully-empty repo).
 *
 * Two kinds:
 *  - {@link REQUIRED_FILES}: repo-root files added when the file is missing.
 *  - {@link REQUIRED_DIRS}: well-known root dirs the app expects to exist; when a
 *    dir is entirely absent it's created by adding its `<dir>/.gitkeep`. Keyed on
 *    the *directory's* existence, not the `.gitkeep` file — so a branch that
 *    already has content under `KnowledgeBase/` never gets a pointless placeholder.
 *
 * `roles.yaml` is in neither, and is not part of the template at all: it is
 * generated from `ADMIN_EMAIL` (see {@link renderRolesYaml}) and written
 * directly, so a repo can't be seeded with a stale hard-coded Admin list.
 */
const REQUIRED_FILES: readonly string[] = ['access.md', 'CLAUDE.md', '.bevelignore', '.gitignore'];
// Required = the app cannot OPERATE without it: `KnowledgeBase/` roots the
// graph, `Groups/` roots skills and tools. `Data/` is not here — it ships in
// the template for fresh seeds, but it is optional records, and a seeder that
// re-creates a folder every time an operator deletes it is worse than no
// seeder (the same reasoning that removed the retired `Agents/`/`Pipelines/`).
const REQUIRED_DIRS: readonly string[] = [KNOWLEDGE_BASE_DIR, GROUPS_DIR];

/** Redact the token from any string that might surface in a log or error. */
function redact(s: string): string {
  const token = process.env.GITHUB_TOKEN;
  return token ? s.replaceAll(token, '***') : s;
}

/** Generate `roles.yaml` granting Admin to each seed email. */
function renderRolesYaml(adminEmails: readonly string[]): string {
  const lines = adminEmails.map((e) => `    - ${e}`).join('\n');
  return (
    '# Identity → role mapping for access control.\n' +
    '# Role names are case- and whitespace-insensitive. The `Admin` role is special:\n' +
    '# only Admins may edit this file, and at least one Admin must always exist.\n' +
    '#\n' +
    '# Generated by the Bevel platform at KB-seed time from ADMIN_EMAIL.\n' +
    'roles:\n' +
    '  Admin:\n' +
    `${lines}\n`
  );
}

/**
 * Seeds/tops-up the KB *remote* so the rest of the app's assumption — that the
 * repo it clones already carries the protected branches and base scaffolding —
 * holds even for a brand-new or partially-populated GitHub repo. The template
 * ships inside the platform (`kb-template/`); this reads from it.
 *
 * Split into two moments so the file-level top-up rides along with the clone the
 * app already performs, rather than doing its own extra clones:
 *  - {@link ensureRemoteSeeded} runs once before the first clone (an empty remote
 *    can't be `clone -b`'d): it seeds an empty repo and makes sure every
 *    protected branch *exists* as a ref.
 *  - {@link topUpWorkspace} runs on the freshly-cloned workspace of whatever
 *    branch a user loads: it fills in any missing base files on that branch.
 */
export class KbSeedService implements IKbSeedService {
  /** Single-flight: the first caller runs the remote pass; the rest await its result. */
  private inFlight: Promise<void> | null = null;

  /**
   * @param kbRepoUrl        Clone/push URL of the KB remote.
   * @param kbTemplateDir    Filesystem path to the `kb-template/` seed source.
   * @param protectedBranches Branch names that must exist (e.g. current/target-company-state).
   * @param defaultBranch    The branch new checkouts land on — used as the init
   *                         branch of the empty-seed commit and the preferred
   *                         base when creating a missing protected branch.
   * @param seedAdminEmails  Admins written into the generated `roles.yaml`.
   * @param gitUsername      Basic-auth username for git-over-HTTPS (provider-specific).
   */
  constructor(
    kbRepoUrl: string | (() => string),
    private readonly kbTemplateDir: string,
    protectedBranches: readonly string[] | (() => readonly string[]),
    defaultBranch: string | (() => string),
    private readonly seedAdminEmails: readonly string[],
    gitUsername: string | (() => string) = 'x-access-token',
  ) {
    // A getter is read per-operation, so a remote supplied through the setup
    // screen is seeded against without restarting; a string is still accepted.
    this.kbRepoUrl = typeof kbRepoUrl === 'function' ? kbRepoUrl : () => kbRepoUrl;
    // Read when seeding, not at construction: the branch model can be supplied
    // through the setup screen, which happens after this object exists.
    this.protectedBranches =
      typeof protectedBranches === 'function' ? protectedBranches : () => protectedBranches;
    this.defaultBranch = typeof defaultBranch === 'function' ? defaultBranch : () => defaultBranch;
    this.gitUsername = typeof gitUsername === 'function' ? gitUsername : () => gitUsername;
  }

  private readonly kbRepoUrl: () => string;
  private readonly protectedBranches: () => readonly string[];
  private readonly defaultBranch: () => string;
  private readonly gitUsername: () => string;

  ensureRemoteSeeded(): Promise<void> {
    // Cache the promise, not just a boolean, so concurrent first-callers share
    // one run. On failure we clear it so a later call can retry (a transient
    // network blip on ls-remote shouldn't wedge seeding for the whole process).
    if (!this.inFlight) {
      this.inFlight = this.run().catch((err) => {
        this.inFlight = null;
        throw err;
      });
    }
    return this.inFlight;
  }

  private async run(): Promise<void> {
    const heads = await this.lsRemoteHeads();

    if (heads.size === 0) {
      if (this.seedAdminEmails.length === 0) {
        throw new Error(
          `KB remote ${redact(this.kbRepoUrl())} is empty and cannot be seeded: ` +
            'no initial Admin was supplied. A seeded KB with no Admin is unusable ' +
            '(access resolution requires at least one Admin). Unreachable in ' +
            'normal operation — ADMIN_EMAIL is required at boot — so this guards ' +
            'a caller that constructed the seeder with an empty list.',
        );
      }
      await this.seedEmptyRemote();
      return;
    }

    // Non-empty remote: make sure every protected branch exists as a ref so a
    // later `clone -b <branch>` succeeds. This creates the branch pointer only;
    // per-branch file top-up happens in `topUpWorkspace` when the branch loads.
    const base = this.pickBase(heads);
    for (const branch of this.protectedBranches()) {
      if (!heads.has(branch)) {
        await this.createBranchOnRemote(branch, base);
      }
    }
  }

  /**
   * Add any missing base scaffolding to an already-cloned workspace of `branch`,
   * then commit + push it. Called once per fresh clone (any branch a user loads),
   * so the check reuses the clone the app already made instead of a dedicated one.
   *
   * Best-effort: never throws. If the push is rejected (e.g. a concurrent update
   * to the branch), the local scaffolding commit is rolled back so the workspace
   * stays consistent with origin, and the top-up is retried on a future clone.
   */
  async topUpWorkspace(repoDir: string, branch: string): Promise<void> {
    // Scaffolding lands on PROTECTED branches only. A draft or suggestions
    // branch is somebody's change-in-waiting, and a seeder commit there
    // surfaces as noise in their change request's diff against the default
    // branch (a stray scaffolding file riding along in a skill proposal was
    // exactly this). Whatever the protected branches are missing, they get
    // when THEY load — and drafts fork from them.
    if (!this.protectedBranches().includes(branch)) return;
    try {
      const added: string[] = [];
      for (const rel of REQUIRED_FILES) {
        if (!(await this.exists(path.join(repoDir, rel)))) {
          await this.copyTemplateFile(rel, repoDir);
          added.push(rel);
        }
      }
      for (const rootDir of REQUIRED_DIRS) {
        if (!(await this.exists(path.join(repoDir, rootDir)))) {
          const keep = `${rootDir}/.gitkeep`;
          await this.copyTemplateFile(keep, repoDir);
          added.push(keep);
        }
      }
      if (!(await this.exists(path.join(repoDir, 'roles.yaml')))) {
        if (this.seedAdminEmails.length > 0) {
          await fs.writeFile(
            path.join(repoDir, 'roles.yaml'),
            renderRolesYaml(this.seedAdminEmails),
            'utf8',
          );
          added.push('roles.yaml');
        } else {
          console.warn(
            `[kb-seed] Branch "${branch}" is missing roles.yaml and ADMIN_EMAIL is ` +
              'unset — leaving it absent. Access resolution will fail until an ' +
              'Admin roles.yaml exists; set ADMIN_EMAIL or add roles.yaml manually.',
          );
        }
      }

      if (added.length === 0) return; // already fully scaffolded → no-op

      // Stamp the bot identity so the commit has an author even if the clone
      // wasn't configured with one (the workspace clone already sets the same
      // values, so this is a harmless no-op there).
      await this.stampIdentity(repoDir);
      await this.git(repoDir, ['add', '--', ...added]);
      await this.git(repoDir, ['commit', '-m', `Add missing KB scaffolding: ${added.join(', ')}`]);
      try {
        await this.git(repoDir, ['push', 'origin', `HEAD:refs/heads/${branch}`]);
        console.log(`[kb-seed] Topped up "${branch}" with: ${added.join(', ')}`);
      } catch (err) {
        // Roll the local branch back to origin so the workspace never sits ahead
        // of the remote (which would confuse the workflow git layer). The files
        // simply aren't present this session; a later fresh clone retries.
        console.warn(
          `[kb-seed] Could not push scaffolding to "${branch}", rolling back local commit:`,
          err instanceof Error ? redact(err.message) : String(err),
        );
        await this.git(repoDir, ['reset', '--hard', `origin/${branch}`]).catch(() => {});
      }
    } catch (err) {
      // Top-up is best-effort infrastructure — a failure here must not block the
      // user from loading the branch.
      console.warn(
        `[kb-seed] Scaffolding top-up for "${branch}" failed (non-fatal):`,
        err instanceof Error ? redact(err.message) : String(err),
      );
    }
  }

  /** Prefer the default branch as a base, else the first protected branch present, else any head. */
  private pickBase(heads: Set<string>): string {
    if (heads.has(this.defaultBranch())) return this.defaultBranch();
    const protectedPresent = this.protectedBranches().find((b) => heads.has(b));
    if (protectedPresent) return protectedPresent;
    // Deterministic pick so repeated runs behave identically.
    return [...heads].sort()[0];
  }

  /** `-c` args that inject credentials + longpaths, mirroring the workspace clone. */
  private credArgs(): string[] {
    const args = ['-c', 'core.longpaths=true'];
    const token = process.env.GITHUB_TOKEN;
    if (token) {
      // The helper reads GITHUB_TOKEN at runtime, so the value never appears in argv.
      // Username is provider-specific; the token is always the Basic-auth password.
      args.push(
        '-c',
        `credential.helper=!f() { echo "username=${this.gitUsername()}"; echo "password=$GITHUB_TOKEN"; }; f`,
      );
    }
    return args;
  }

  private async git(cwd: string | null, args: string[]): Promise<string> {
    try {
      const { stdout } = await execFileAsync('git', args, {
        cwd: cwd ?? undefined,
        env: { ...process.env, LC_ALL: 'C', LANG: 'C' },
        maxBuffer: 32 * 1024 * 1024,
      });
      return stdout.toString();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      let i = 0;
      while (i < args.length && args[i] === '-c') i += 2;
      throw new Error(`git ${args[i] ?? args[0]} failed: ${redact(msg)}`);
    }
  }

  /** Set of branch names on the remote (empty ⇒ uninitialised repo). */
  private async lsRemoteHeads(): Promise<Set<string>> {
    const out = await this.git(null, [...this.credArgs(), 'ls-remote', '--heads', this.kbRepoUrl()]);
    const heads = new Set<string>();
    for (const line of out.split('\n')) {
      const m = line.match(/\srefs\/heads\/(.+)$/);
      if (m) heads.add(m[1].trim());
    }
    return heads;
  }

  /** Run a block against a throwaway temp dir, always cleaned up. */
  private async withTempDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kb-seed-'));
    try {
      return await fn(dir);
    } finally {
      await fs.rm(dir, { recursive: true, force: true }).catch(() => {});
    }
  }

  private async stampIdentity(repo: string): Promise<void> {
    await this.git(repo, ['config', 'user.name', BOT_NAME]);
    await this.git(repo, ['config', 'user.email', BOT_EMAIL]);
  }

  /** Copy the entire template tree into `dest` (roles.yaml isn't in it — it's generated). */
  private async copyTemplateTree(dest: string): Promise<void> {
    const walk = async (relDir: string): Promise<void> => {
      const abs = path.join(this.kbTemplateDir, relDir);
      const entries = await fs.readdir(abs, { withFileTypes: true });
      for (const entry of entries) {
        const rel = relDir ? path.join(relDir, entry.name) : entry.name;
        if (entry.isDirectory()) {
          await walk(rel);
        } else {
          await this.copyTemplateFile(rel, dest);
        }
      }
    };
    await walk('');
  }

  /** Copy one template file (by repo-relative path) into `dest`, creating parents. */
  private async copyTemplateFile(relPath: string, dest: string): Promise<void> {
    const from = path.join(this.kbTemplateDir, relPath);
    const to = path.join(dest, relPath);
    await fs.mkdir(path.dirname(to), { recursive: true });
    await fs.copyFile(from, to);
  }

  /** `git init` a temp repo, lay down the full template + generated roles.yaml, commit. */
  private async buildSeedCommit(dir: string): Promise<void> {
    await this.git(dir, ['init', '-b', this.defaultBranch()]);
    await this.stampIdentity(dir);
    await this.copyTemplateTree(dir);
    await fs.writeFile(path.join(dir, 'roles.yaml'), renderRolesYaml(this.seedAdminEmails), 'utf8');
    await this.git(dir, ['add', '-A']);
    await this.git(dir, ['commit', '-m', 'Seed knowledge base from Bevel template']);
  }

  /** Empty remote → one seed commit pushed to every protected branch. */
  private async seedEmptyRemote(): Promise<void> {
    await this.withTempDir(async (dir) => {
      await this.buildSeedCommit(dir);
      // Point every protected branch at the seed commit. The init branch is
      // already `defaultBranch`; create the rest as refs to HEAD.
      for (const branch of this.protectedBranches()) {
        if (branch !== this.defaultBranch()) {
          await this.git(dir, ['branch', branch]);
        }
      }
      await this.git(dir, ['remote', 'add', 'origin', this.kbRepoUrl()]);
      // Push only the protected branches — never the stray init branch if it
      // isn't itself protected.
      await this.git(dir, [...this.credArgs(), 'push', '-u', 'origin', ...this.protectedBranches()]);
      console.log(
        `[kb-seed] Seeded empty KB remote with branches: ${this.protectedBranches().join(', ')}`,
      );
    });
  }

  /** Create a missing protected branch on the remote, pointed at `base`'s tip. */
  private async createBranchOnRemote(branch: string, base: string): Promise<void> {
    await this.withTempDir(async (dir) => {
      await this.git(dir, [...this.credArgs(), 'clone', '--depth', '1', '-b', base, this.kbRepoUrl(), dir]);
      // Push base's fetched tip up under the new branch name.
      await this.git(dir, [...this.credArgs(), 'push', 'origin', `HEAD:refs/heads/${branch}`]);
      console.log(`[kb-seed] Created missing protected branch "${branch}" from "${base}"`);
    });
  }

  private async exists(p: string): Promise<boolean> {
    try {
      await fs.access(p);
      return true;
    } catch {
      return false;
    }
  }
}
