import fs from 'node:fs/promises';
import path from 'node:path';
import { parseRolesYaml } from '../../../access/access-control.service.js';
import type { OnServerStart, ServerStartContext, StepResult } from '../on-server-start.js';

/**
 * Generate `roles.yaml` granting Admin to each seed email.
 *
 * Each email is validated first, because a malformed one renders a file with
 * no working Admin — SILENTLY: a leading `#` turns the entry into a YAML
 * comment, an embedded newline breaks the list, an all-whitespace value
 * renders an empty entry. A bad ADMIN_EMAIL is operator error, and under the
 * startup phase's fail-closed contract it stops the boot with a message
 * naming the fix instead of seeding an un-administrable knowledge base.
 */
export function renderRolesYaml(adminEmails: readonly string[]): string {
  const emails = adminEmails.map((raw) => {
    const email = raw.trim();
    if (email === '') {
      throw new Error('Seed admin email is empty — set ADMIN_EMAIL to a real address.');
    }
    if (email.startsWith('#')) {
      throw new Error(
        `Seed admin email ${JSON.stringify(raw)} starts with "#", which YAML reads as a comment — fix ADMIN_EMAIL.`,
      );
    }
    if (/\s/.test(email)) {
      throw new Error(
        `Seed admin email ${JSON.stringify(raw)} contains whitespace, which would corrupt roles.yaml — fix ADMIN_EMAIL.`,
      );
    }
    return email;
  });
  const lines = emails.map((e) => `    - ${e}`).join('\n');
  const text =
    '# Identity → role mapping for access control.\n' +
    '# Role names are case- and whitespace-insensitive. The `Admin` role is special:\n' +
    '# only Admins may edit this file, and at least one Admin must always exist.\n' +
    '#\n' +
    '# Generated by the Bevel platform at KB-seed time from ADMIN_EMAIL.\n' +
    'roles:\n' +
    '  Admin:\n' +
    `${lines}\n`;
  // Validate by PARSING with the real access parser, not by re-implementing
  // its email grammar: whatever the parser would reject (a `<Name <email>`
  // shape, a non-email string, tomorrow's new rule) must stop the boot here,
  // before an un-administrable roles.yaml gets committed. The checks above
  // exist only to give the common mistakes sharper messages.
  const parsed = parseRolesYaml(text);
  if (!parsed.ok) {
    throw new Error(
      `Generated roles.yaml from ADMIN_EMAIL would not parse — fix the configured address(es). ` +
        parsed.errors.join('; '),
    );
  }
  return text;
}

/**
 * Write `roles.yaml` on any protected branch missing it, generated from the
 * configured seed admins (`ADMIN_EMAIL`). Never part of the template: a
 * template copy would seed repos with a stale hard-coded Admin list.
 *
 * An existing file — whatever it says — is the operator's and is left alone.
 *
 * A missing file with NO admins configured is a declared `skipped`: the lazy
 * top-up warned and left the file absent, and under the startup contract that
 * survivable-but-incomplete state is the step's to declare, not to bury in a
 * log. Access resolution will fail until an Admin roles.yaml exists.
 */
export class RolesYamlStep implements OnServerStart {
  readonly name = 'roles-yaml';

  constructor(private readonly seedAdminEmails: readonly string[]) {}

  async run(ctx: ServerStartContext): Promise<StepResult> {
    const adminless: string[] = [];
    for (const branch of await ctx.protectedBranches()) {
      const repoDir = await branch.repoDir();
      if (await exists(path.join(repoDir, 'roles.yaml'))) continue;
      if (this.seedAdminEmails.length === 0) {
        adminless.push(branch.name);
        continue;
      }
      branch.write('roles.yaml', renderRolesYaml(this.seedAdminEmails));
      branch.note('Add roles.yaml granting Admin to the configured seed admins');
    }
    if (adminless.length > 0) {
      // With an empty admin list nothing was declared for ANY branch, so the
      // skip discards nothing another branch needed.
      return {
        outcome: 'skipped',
        reason:
          `roles.yaml is missing on ${adminless.join(', ')} and ADMIN_EMAIL is unset — leaving it absent. ` +
          'Access resolution will fail until an Admin roles.yaml exists; set ADMIN_EMAIL or add roles.yaml manually.',
      };
    }
    return { outcome: 'ok' };
  }
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
