import fs from 'node:fs/promises';
import path from 'node:path';
import type { OnServerStart, ServerStartContext, StepResult } from '../on-server-start.js';

/** Generate `roles.yaml` granting Admin to each seed email. */
export function renderRolesYaml(adminEmails: readonly string[]): string {
  const lines = adminEmails.map((e) => `    - ${e}`).join('\n');
  return (
    '# Identity → role mapping for access control.\n' +
    '# Role names are case- and whitespace-insensitive. The `Admin` role is special:\n' +
    '# only Admins may edit this file, and at least one Admin must always exist.\n' +
    '#\n' +
    '# Generated by the Bevel platform at KB-seed time from ADMIN_EMAIL.\n' +
    'roles:\n' +
    '  Admin:\n' +
    `${lines}\n`
  );
}

/**
 * Write `roles.yaml` on any protected branch missing it, generated from the
 * configured seed admins (`ADMIN_EMAIL`). Never part of the template: a
 * template copy would seed repos with a stale hard-coded Admin list.
 *
 * An existing file — whatever it says — is the operator's and is left alone.
 *
 * A missing file with NO admins configured is a declared `skipped`: the lazy
 * top-up warned and left the file absent, and under the startup contract that
 * survivable-but-incomplete state is the step's to declare, not to bury in a
 * log. Access resolution will fail until an Admin roles.yaml exists.
 */
export class RolesYamlStep implements OnServerStart {
  readonly name = 'roles-yaml';

  constructor(private readonly seedAdminEmails: readonly string[]) {}

  async run(ctx: ServerStartContext): Promise<StepResult> {
    const adminless: string[] = [];
    for (const branch of await ctx.protectedBranches()) {
      const repoDir = await branch.repoDir();
      if (await exists(path.join(repoDir, 'roles.yaml'))) continue;
      if (this.seedAdminEmails.length === 0) {
        adminless.push(branch.name);
        continue;
      }
      branch.write('roles.yaml', renderRolesYaml(this.seedAdminEmails));
      branch.note('Add roles.yaml granting Admin to the configured seed admins');
    }
    if (adminless.length > 0) {
      // With an empty admin list nothing was declared for ANY branch, so the
      // skip discards nothing another branch needed.
      return {
        outcome: 'skipped',
        reason:
          `roles.yaml is missing on ${adminless.join(', ')} and ADMIN_EMAIL is unset — leaving it absent. ` +
          'Access resolution will fail until an Admin roles.yaml exists; set ADMIN_EMAIL or add roles.yaml manually.',
      };
    }
    return { outcome: 'ok' };
  }
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
